name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      MAINNET_SECRET_WORDS: ${{ secrets.TEST_WALLET_SEED_PHRASE }}
      SECRET_WORDS: ${{ secrets.TEST_WALLET_SEED_PHRASE }}
      PASSWORD: TestMetaMask
      NETWORK_NAME: tenderly
      RPC_URL: ${{ secrets.DUMMY_RPC_URL }}
      CHAIN_ID: 1
      CYPRESS_TENDERLY_KEY: ${{ secrets.CYPRESS_TENDERLY_KEY }}
      CYPRESS_TENDERLY_PROJECT: ${{ secrets.CYPRESS_TENDERLY_PROJECT }}
    steps:
      - run: sudo apt-get install xvfb
      - run: sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install chrome
        uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - run: yarn install
      - run: yarn build:testing
      - run: yarn serve -l 3000 &
      - run: yarn cypress:ci
